### ping
GET {{baseUrl}}/ping

### register user
POST {{baseUrl}}/api/user/register
Content-Type: application/json

{
  "login": "test@gmail.com",
  "password": "fh49t3jrojf"
}

### login user
POST {{baseUrl}}/api/user/login
Content-Type: application/json

{
  "login": "test@gmail.com",
  "password": "fh49t3jrojf"
}

### load order
POST {{baseUrl}}/api/user/orders
Content-Type: text/plain
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTk5OTg5NjcsIlVzZXJJRCI6ImYzMzc1YWI3LWEwMDAtNDk5Ny1iNmNhLTA3YmQ1YWMwMWZhYyJ9.AnR-ne7wuKlbEzkTjDkplFujdLK1uYyW4U-J_IXUw2c

123456782

### get orders
GET {{baseUrl}}/api/user/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTk4MDIyODgsIlVzZXJJRCI6ImYzMzc1YWI3LWEwMDAtNDk5Ny1iNmNhLTA3YmQ1YWMwMWZhYyJ9.4wMlGDgmey9gRH5RvLqMlNQFYLIOq9sUQtPsLuGUSQY

### get user balance
GET {{baseUrl}}/api/user/balance
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDAwODk1NDYsIlVzZXJJRCI6ImYzMzc1YWI3LWEwMDAtNDk5Ny1iNmNhLTA3YmQ1YWMwMWZhYyJ9._hLuquyaTrvJdXQxYh3ngnmdznj9gbvZeqFjsKUjIDI
