### ping
GET {{baseUrl}}/ping

### register user
POST {{baseUrl}}/api/user/register
Content-Type: application/json

{
  "login": "test@gmail.com",
  "password": "fh49t3jrojf"
}

### login user
POST {{baseUrl}}/api/user/login
Content-Type: application/json

{
  "login": "test@gmail.com",
  "password": "fh49t3jrojf"
}

### load order
POST {{baseUrl}}/api/user/orders
Content-Type: text/plain
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTk3ODk5MjMsIlVzZXJJRCI6ImYzMzc1YWI3LWEwMDAtNDk5Ny1iNmNhLTA3YmQ1YWMwMWZhYyJ9.XROZ47eVxb1RSGjFd-T3y4uBgdO0u6YwP5PUQH_T9Jw

123456782

### get orders
GET {{baseUrl}}/api/user/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTk4MDIyODgsIlVzZXJJRCI6ImYzMzc1YWI3LWEwMDAtNDk5Ny1iNmNhLTA3YmQ1YWMwMWZhYyJ9.4wMlGDgmey9gRH5RvLqMlNQFYLIOq9sUQtPsLuGUSQY
