### ping
GET {{baseUrl}}/ping

### register user
POST {{baseUrl}}/api/user/register
Content-Type: application/json

{
  "login": "test@gmail.com",
  "password": "fh49t3jrojf"
}

### login user
POST {{baseUrl}}/api/user/login
Content-Type: application/json

{
  "login": "test@gmail.com",
  "password": "fh49t3jrojf"
}

### load order
POST {{baseUrl}}/api/user/orders
Content-Type: text/plain
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDAzMTMwNzgsIlVzZXJJRCI6ImYzMzc1YWI3LWEwMDAtNDk5Ny1iNmNhLTA3YmQ1YWMwMWZhYyJ9.5Nyfucn8uOLm5EXR2CViQdcq7ZGaaN3ONMFiDRMj_vc

123456782

### get orders
GET {{baseUrl}}/api/user/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDAzMjUwNjgsIlVzZXJJRCI6ImE0MjcxYTAzLWY1ZWItNDk4My1hNWJlLTg3MDIwMjU2YTFmMSJ9.mXbmbOgHMmUMOqtuPAgOtLFufp0Ud_jL5AWEKXJRQeE


### get user balance
GET {{baseUrl}}/api/user/balance
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDAzMTMwNzgsIlVzZXJJRCI6ImYzMzc1YWI3LWEwMDAtNDk5Ny1iNmNhLTA3YmQ1YWMwMWZhYyJ9.5Nyfucn8uOLm5EXR2CViQdcq7ZGaaN3ONMFiDRMj_vc


### withdraw
POST {{baseUrl}}/api/user/balance/withdraw
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDAzMTMwNzgsIlVzZXJJRCI6ImYzMzc1YWI3LWEwMDAtNDk5Ny1iNmNhLTA3YmQ1YWMwMWZhYyJ9.5Nyfucn8uOLm5EXR2CViQdcq7ZGaaN3ONMFiDRMj_vc
Content-Type: application/json

{
  "order": "2377225624",
  "sum": 10
}

### get withdrawals
GET {{baseUrl}}/api/user/withdrawals
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDAzMTMwNzgsIlVzZXJJRCI6ImYzMzc1YWI3LWEwMDAtNDk5Ny1iNmNhLTA3YmQ1YWMwMWZhYyJ9.5Nyfucn8uOLm5EXR2CViQdcq7ZGaaN3ONMFiDRMj_vc
